TITLE = 'MCP Toolbox 数据库小白指南'
SUBTITLE = '12 个疑问 · 5 项能力 · 1 个真实只读边界实验'
HEAD = 'a24e5e68567fa014a42fc6cc711faa82b964d4c0'
RELEASE = 'e14cda6b4f483e6b5e5ec23e342f9f232a6ce60f'
BASE = 'https://github.com/googleapis/mcp-toolbox/blob/' + HEAD + '/'
QUESTIONS = [
dict(title='它是数据库，还是让 AI 使用数据库的接线员？',
lead='Toolbox 是工具服务器；真正存数据、执行 SQL 的仍是数据库。',
answer='想象客服助手收到“查一下上海的酒店”。模型理解需求，客户端发出工具调用，Toolbox 把已配置的查询交给数据库，再把结果传回。它不是大模型，也不会凭空知道你的表结构。项目把数据库连接、工具定义和调用接口集中起来，减少每个助手重复造接线代码。',
term='MCP（Model Context Protocol，模型上下文协议）约定客户端与工具服务器如何交换能力和请求；SQL 是关系数据库的查询语言。',
example='例子：输入城市只是参数，酒店表和结果来自数据库，不是模型“记住”的答案。',
nodes=['助手客户端','Toolbox','SQLite 数据库'], caption='需求被翻译为工具调用；结果沿原路返回。',
refs=['README.md','docs/en/documentation/introduction/_index.md']),
dict(title='我学过 MCP 了，为什么还要学 Toolbox？',
lead='MCP 是接口约定，Toolbox 是实现数据库工具的一套具体软件。',
answer='把 MCP 类比成插座规格，Toolbox 是有多种数据库插口的设备。会用 MCP 客户端，不等于已经定义好数据库查询。本项目提供两条入口：开发时使用预置通用工具探索数据；应用运行时提供围绕业务设计的自定义工具。两者风险和可控范围不同。',
term='预置工具是项目打包好的通用能力；自定义工具是你用配置写明用途、参数和执行逻辑的能力。',
example='例子：开发者可以探索表结构；面向客户的助手通常只需“按订单号查状态”，不必获得任意 SQL。',
nodes=['MCP 约定','具体工具实现','业务可用能力'], caption='已有 MCP 概念只复用，不把协议与产品混成一个词。',
refs=['README.md']),
dict(title='Source、Tool、Toolset 到底各管什么？',
lead='Source 连哪里，Tool 做什么，Toolset 一次加载哪些工具。',
answer='Source（数据源）保存数据库类型和连接信息；Tool（工具）定义可调用操作；Toolset（工具集）把工具按用途分组。比如酒店数据库是一个 source，按城市查询是一个 tool，客服常用查询放进一个 toolset。分组让客户端少看无关工具，但分组本身不能代替权限。',
term='配置是服务器启动时读取的结构化说明。固定文档将 toolset 视为仅含工具的 group（组）；旧配置仍兼容，但 description 等字段有例外，应核对版本。',
example='例子：同一个数据库可被多个工具复用，同一个查询工具也可出现在不同工具集中。',
nodes=['source：酒店库','tool：按城市查','toolset：客服'], caption='连接、动作、打包分层，修改时才知道该动哪一层。',
refs=['README.md','docs/en/documentation/configuration/toolsets/_index.md']),
dict(title='参数绑定为什么比拼接 SQL 更稳妥？',
lead='把输入当作值传进去，不让输入变成 SQL 结构。',
answer='sqlite-sql 的普通参数按顺序绑定到问号占位符。城市名即使含引号，也应作为城市值处理，而不是拼成新的 WHERE 条件。类型检查还能提前发现把整数传进字符串参数的错误。参数化减少值注入风险，却不能替你决定谁有权查这行数据。',
term='占位符是 SQL 中等待填入“值”的位置；参数绑定由驱动传递值。templateParameters 则先替换 SQL 文本，作用不同，风险也更高。',
example='例子：WHERE city = ? 可以绑定城市；不能靠 ? 动态替换表名。表名需求应优先改为固定工具或受控映射。',
nodes=['输入城市值','绑定到 ?','固定 SQL 结构'], caption='值进入指定槽位；不把用户文本直接当查询代码。',
refs=['docs/en/integrations/sqlite/tools/sqlite-sql.md']),
dict(title='能直接执行任意 SQL，为什么还要写专用工具？',
lead='通用 SQL 很灵活；专用工具更容易定义、检查和限制业务范围。',
answer='sqlite-execute-sql 接收一段 SQL，适合有人监督的开发探索。sqlite-sql 则把语句固定在配置里，只开放必要参数。固定语句更便于审阅、测试和限定返回字段，但仍可能是一条写语句。工具名字叫“查询”或描述写“安全”都不构成限制。',
term='最小权限是只授予任务必要的能力；它必须落实在可用工具、认证授权和数据库权限等实际机制中。',
example='例子：客服只需要订单状态，不应默认能列出整张客户表。官方 SQLite 通用 SQL 文档明确提醒其不适用于生产代理。',
nodes=['通用 SQL 探索','固定业务 SQL','最小必要字段'], caption='按场景收窄输入面，再检查数据库底层权限。',
refs=['docs/en/integrations/sqlite/tools/sqlite-execute-sql.md','docs/en/integrations/sqlite/tools/sqlite-sql.md']),
dict(title='把写工具从列表隐藏，等于禁止写入了吗？',
lead='工具清单是可发现范围；写入权限是另一道需要实测的边界。',
answer='toolset 让某个客户端加载一组工具，减少干扰和误调用。判断安全边界时，还要问：服务器是否仍注册其他工具？其他入口能否调用？数据库连接是否允许写？本实验会比较工具列表与实际调用结果，而不是看到菜单变短就宣布数据库只读。',
term='发现（discovery）是询问有哪些工具；调用（invocation）是请求执行某个工具。清单里的提示不是数据库的授权判决。',
example='例子：菜单没有“修改价格”不等于厨房没有这道操作。要用受控写入测试与数据前后对照确认边界。',
nodes=['tools/list 清单','tools/call 请求','数据库裁决'], caption='分别收集三层证据，不能用第一层替代第三层。',
refs=['docs/en/documentation/configuration/toolsets/_index.md','docs/en/documentation/configuration/security/read-only.md']),
dict(title='readOnly、readOnlyHint、SQLite mode=ro 是同一件事吗？',
lead='不是。提示、Toolbox 功能和数据库连接方式属于不同层。',
answer='readOnlyHint 是给客户端的行为注解，不是权限证明。部分受支持数据源的 readOnly 功能会配合底层限制、工具裁剪和注解；当前文档矩阵列出 Cloud SQL PostgreSQL、Cloud SQL MySQL、AlloyDB PostgreSQL 和 BigQuery。SQLite 源没有这个 readOnly 配置字段，源码中的 IsReadOnly 返回 false。',
term='SQLite URI 的 mode=ro 表示该数据库文件以只读方式打开。本实验利用驱动接受的 URI，实测对该文件的写入失败；这不等于验证了上述云数据库机制。',
example='例子：实验保留写工具并真正调用它。预期写失败、数据不变；不会使用 SQL 关键词过滤器充当安全边界。',
nodes=['Hint：告诉客户端','readOnly：限支持源','mode=ro：本实验'], caption='SQLite 只读文件连接不自动证明工具被裁剪或注解正确。',
refs=['docs/en/documentation/configuration/security/read-only.md','internal/sources/sqlite/sqlite.go']),
dict(title='登录成功，为什么也未必能读所有数据？',
lead='身份验证说明“你是谁”；授权还要回答“你能做什么”。',
answer='Toolbox 可按工具检查令牌，也可把身份声明绑定到参数；数据库自身还可通过账号权限限制访问。应用应避免让模型随意填写他人的用户编号，再把它当可信身份。跨用户、跨租户的数据隔离必须在可信层校验，不能只写进提示词。',
term='认证是核实身份；授权是决定允许的动作和数据范围。OIDC 是传递身份信息的标准；claim 是令牌中经验证的身份字段。',
example='例子：用户 A 的订单工具应使用可信身份限定 A 的记录。即使请求参数写成 B，也不应扩大到 B 的订单。该身份流程本次没有配置或验证。',
nodes=['核实调用者身份','绑定可信用户范围','DB 权限再限制'], caption='本实验仅用虚构数据，不访问账号、令牌或真实客户数据。',
refs=['docs/en/documentation/configuration/authentication/_index.md']),
dict(title='stdio 和 HTTP 只是启动方式不同吗？',
lead='它们也是不同的连接方式和部署边界。',
answer='stdio 用进程的标准输入输出传递 MCP 消息，常见于本地客户端启动工具服务器；HTTP 通过网络端点连接，更适合独立部署但需要考虑暴露范围、认证和网络保护。本实验通过 stdio 启动官方二进制，不监听端口，不修改任何 MCP 客户端的全局配置。',
term='传输层是消息在客户端与服务器之间走的通道。JSON-RPC 是本实验 MCP 请求使用的消息格式，带有方法名、参数和请求编号。',
example='例子：脚本发送 tools/list，再发送 tools/call，并把实际响应记入日志。无需模型或付费 API 也能测试这个协议环节。',
nodes=['Python 测试脚本','stdin / stdout','Toolbox 子进程'], caption='真实工具服务器运行；模型规划质量不在本次测试范围内。',
refs=['docs/en/documentation/connect-to/mcp-client/_index.md','README.md']),
dict(title='看到“调用成功”，怎样知道到底发生了什么？',
lead='同时看响应、错误和数据库状态，才有完整证据链。',
answer='只看进程退出码会漏掉协议内的工具错误。测试应记录请求目标、参数、结果和错误，再比较数据前后状态。Toolbox 支持 OpenTelemetry 的链路与指标，但部署采集器和外部后端是另一项工作。本次只保留项目内测试日志，不向遥测服务发送数据。',
term='可观测性是通过日志、指标和链路了解系统运行；审计记录用于回溯“谁在何时做了什么”。测试日志不等于生产审计体系。',
example='例子：本次主库读到 2 行、写调用返回只读错误、再次读取仍为 2 行，三份证据比“安全测试通过”一句话更可信。日志应避免记录令牌与真实敏感字段。',
nodes=['请求与响应','检查错误内容','核对数据未变'], caption='成功读取、预期拒绝、反例对照都应留下记录。',
refs=['README.md','docs/en/documentation/monitoring/export_telemetry.md']),
dict(title='我只改了一行配置，结果为什么变了？',
lead='配置也是可执行行为的一部分，需要版本、校验和回归测试。',
answer='Toolbox 可动态重载配置，因此改 source 或 statement 可能直接改变工具行为。实验固定官方二进制版本、文件 SHA-256 和运行配置，避免“昨天的文档配今天的程序”。源码 HEAD 与发布版本分开记录；遇到字段不识别，应核对该版本支持范围，不可静默删掉限制继续运行。',
term='版本固定是使用明确的版本或提交；SHA-256 是文件指纹，用于确认字节是否一致。它本身不证明文件来自可信发布者。',
example='例子：SQLite 源写入 readOnly: true 若被拒绝，正确结论是“该字段不受支持”，不是“只读已打开”。本实验会保留真实报错证据。',
nodes=['固定版本与来源','验证配置加载','复跑读写对照'], caption='官方渠道、文件指纹、实际行为是互补证据。',
refs=['README.md','internal/sources/sqlite/sqlite.go']),
dict(title='做完这次实验，可以直接连生产数据库了吗？',
lead='先把小实验变成清楚的验收清单，再决定部署。',
answer='本次只证明固定版本在虚构 SQLite 文件上的特定行为。生产环境还要验证目标数据库权限、租户隔离、返回数据最小化、认证、超时与资源限制、敏感日志处理和回滚方案。即使一个写操作被拒绝，也不能推断所有文件、所有数据库或所有工具都安全。',
term='威胁模型是列清楚要保护的资产、可能的攻击路径和信任边界；回归测试是在改动后重复检查原有保证。',
example='下一步：用脱敏测试库和真正的最小权限账号，补上越权、写入、超时、错误响应测试。只有授权和验收都明确后才考虑真实环境。',
nodes=['本次 SQLite 证据','目标环境专项测试','授权后的部署'], caption='把结论带着适用范围一起迁移，避免小实验被放大。',
refs=['docs/en/documentation/configuration/security/read-only.md','docs/en/documentation/configuration/authentication/_index.md'])
]

ABILITIES = [
('连接多种数据源', '通过各类型 source 复用数据库连接；具体支持字段和权限须按版本、数据库检查。'),
('提供预置与专用工具', '开发时探索表结构；运行时用固定 SQL 与类型化参数表达业务操作。'),
('按应用组织工具', '把需要一起加载的工具归为 toolset，减少客户端无关能力与上下文负担。'),
('接入身份与权限机制', '按工具验证身份或绑定可信身份参数；配合数据库权限，不能由描述文字替代。'),
('记录运行与诊断信号', '支持连接管理、日志和 OpenTelemetry；真正的采集、保留与脱敏还需配置。')
]
USES = [
('练习数据库助手', '用虚构酒店表测试 MCP 列表、参数绑定和错误处理，不需要大模型或真实账号。'),
('做固定业务查询', '把“查订单状态”“统计当日库存”做成小而清楚的工具，并由可信身份限定数据。'),
('辅助开发探索', '在隔离测试库中查看表与查询数据，通用 SQL 操作保留人工监督。'),
('复用工具服务', '让不同 MCP 客户端或 Toolbox SDK 使用同一套经过测试的业务工具。')
]

SOURCE_FILES = [
('项目与安装', 'README.md'),
('SQLite 数据源', 'docs/en/integrations/sqlite/source.md'),
('参数化 SQLite SQL', 'docs/en/integrations/sqlite/tools/sqlite-sql.md'),
('通用 SQLite SQL', 'docs/en/integrations/sqlite/tools/sqlite-execute-sql.md'),
('工具集', 'docs/en/documentation/configuration/toolsets/_index.md'),
('只读支持矩阵', 'docs/en/documentation/configuration/security/read-only.md'),
('身份验证', 'docs/en/documentation/configuration/authentication/_index.md'),
('SQLite 源实现', 'internal/sources/sqlite/sqlite.go'),
('MCP 客户端连接', 'docs/en/documentation/connect-to/mcp-client/_index.md'),
('遥测导出', 'docs/en/documentation/monitoring/export_telemetry.md')
]
